all:
	pandoc --pdf-engine=xelatex -V "mainfont:Iosevka Nerd Font" -V geometry:margin=0.25in -V "monofont:Iosevka Nerd Font" --highlight-style=breezedark .\senior-swe-techincal-guide.md -o .\senior-swe-techincal-guide.pdf
